"""
combine_for_ai.py
=================
Combines the source files of this project into a single text file
(``combined_code.txt``) so that the entire codebase can be fed to an AI
model in one shot.

The script is opinionated about what counts as "necessary":

  INCLUDED
  --------
  * Source code          -> .ts .tsx .js .jsx .mjs .cjs .py
  * Type / schema        -> .d.ts
  * Style / markup       -> .css .scss
  * Config (curated)     -> package.json, tsconfig.json, next.config.*,
                             postcss.config.*, eslint.config.*,
                             .gitignore, middleware.ts
  * Documentation        -> .md  (README, AGENTS, CLAUDE, REPORT, etc.)
  * Database / migrations -> .sql

  EXCLUDED
  --------
  * Dependency trees       -> node_modules, .pnpm-store
  * Version control        -> .git
  * Build / cache output   -> .next, dist, build, out, coverage
  * Lock files (huge)      -> package-lock.json, pnpm-lock.yaml,
                              yarn.lock, composer.lock
  * Editor settings        -> .vscode, .idea
  * OS metadata            -> .DS_Store, Thumbs.db
  * Generated type info    -> *.tsbuildinfo
  * Binary assets          -> .pdf, .png, .jpg, .jpeg, .gif, .ico,
                              .woff, .woff2, .ttf, .eot
  * Public static assets   -> .svg (in /public)  [the project only
                              uses decorative SVGs in /public]

Usage
-----
    python combine_for_ai.py                # writes ./combined_code.txt
    python combine_for_ai.py output.txt     # custom output filename
    python combine_for_ai.py --stdout       # print to stdout instead
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #

# File extensions we treat as source / config / docs worth including.
INCLUDED_EXTENSIONS: set[str] = {
    # Source code
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py",
    # Type & style
    ".d.ts", ".css", ".scss", ".sass",
    # Database
    ".sql",
    # Documentation
    ".md", ".mdx",
    # Misc text
    ".json", ".yaml", ".yml", ".toml", ".env.example",
}

# Whole directories we never want to walk into.
EXCLUDED_DIRS: set[str] = {
    "node_modules",
    ".git",
    ".next",
    ".turbo",
    ".vercel",
    "dist",
    "build",
    "out",
    "coverage",
    ".vscode",
    ".idea",
    ".DS_Store",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
}

# Individual files we skip even if their extension is on the allow-list.
EXCLUDED_FILES: set[str] = {
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "composer.lock",
    "tsconfig.tsbuildinfo",
    "next-env.d.ts",  # auto-generated by Next.js
    "next.config.ts.bak",
    ".env",
    ".env.local",
    ".env.production",
    ".env.development",
    "combined_code.txt",       # don't include the script's own output
    "combined_code_for_ai.txt",# alternate output name
    "combine_for_ai.py",       # the script itself
    "combiner.py",             # the older script
}

# Specific large / binary files that we *could* match by extension but
# explicitly want to skip.
EXCLUDED_EXTENSIONS: set[str] = {
    ".pdf", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp",
    ".ico", ".woff", ".woff2", ".ttf", ".eot", ".otf",
    ".mp4", ".mov", ".mp3", ".wav", ".zip", ".tar", ".gz",
    ".pyc", ".so", ".dll", ".exe",
}

# Maximum size (in bytes) of any single file we will inline.  Files larger
# than this are listed but not embedded, to keep the output manageable.
MAX_FILE_SIZE = 200_000  # 200 KB

# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

SEPARATOR = "=" * 80


def is_excluded_dir(dirname: str) -> bool:
    return dirname in EXCLUDED_DIRS or dirname.startswith(".") and dirname not in {".github"}


def should_skip_file(path: Path) -> bool:
    """Return True if ``path`` should not be included in the bundle."""
    if path.name in EXCLUDED_FILES:
        return True
    if path.suffix.lower() in EXCLUDED_EXTENSIONS:
        return True
    if path.suffix.lower() not in INCLUDED_EXTENSIONS:
        return True
    return False


def iter_candidate_files(root: Path) -> Iterable[Path]:
    """Yield candidate files under ``root`` that are not in excluded dirs."""
    for item in sorted(root.rglob("*")):
        if not item.is_file():
            continue
        # Skip anything inside an excluded directory.
        if any(part in EXCLUDED_DIRS for part in item.relative_to(root).parts):
            continue
        if should_skip_file(item):
            continue
        yield item


def make_relative_label(root: Path, file: Path) -> str:
    """Return a human-friendly label like './src/app/page.tsx'."""
    rel = file.relative_to(root).as_posix()
    return f"./{rel}" if not rel.startswith("./") else rel


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def combine(root: Path, out_handle) -> tuple[int, int, int]:
    """
    Walk the project and write each included file to ``out_handle``.
    Returns a tuple of (files_written, files_skipped_large, files_skipped_err).
    """
    written = 0
    skipped_large = 0
    skipped_err = 0
    total_bytes = 0

    # Header / manifest
    out_handle.write(f"{SEPARATOR}\n")
    out_handle.write("PROJECT BUNDLE — generated by combine_for_ai.py\n")
    out_handle.write(f"Root: {root.resolve()}\n")
    out_handle.write(f"{SEPARATOR}\n\n")

    # First, list every file we are going to include (manifest).
    candidates = list(iter_candidate_files(root))
    out_handle.write(f"FILES INCLUDED ({len(candidates)}):\n")
    out_handle.write("-" * 80 + "\n")
    for f in candidates:
        try:
            size = f.stat().st_size
        except OSError:
            size = -1
        out_handle.write(f"  {size:>8} B  {make_relative_label(root, f)}\n")
    out_handle.write("\n" + SEPARATOR + "\n\n")

    # Then dump every file.
    for f in candidates:
        label = make_relative_label(root, f)
        try:
            size = f.stat().st_size
        except OSError as exc:
            out_handle.write(f"{SEPARATOR}\nFILE: {label}\n{SEPARATOR}\n")
            out_handle.write(f"[stat error: {exc}]\n\n")
            skipped_err += 1
            continue

        out_handle.write(f"{SEPARATOR}\n")
        out_handle.write(f"FILE: {label}  ({size} bytes)\n")
        out_handle.write(f"{SEPARATOR}\n\n")

        if size > MAX_FILE_SIZE:
            out_handle.write(
                f"[file omitted — {size} bytes exceeds MAX_FILE_SIZE "
                f"({MAX_FILE_SIZE}).  Inspect it manually if needed.]\n\n"
            )
            skipped_large += 1
            continue

        try:
            content = f.read_text(encoding="utf-8", errors="replace")
        except Exception as exc:  # noqa: BLE001 — best effort
            out_handle.write(f"[read error: {exc}]\n\n")
            skipped_err += 1
            continue

        out_handle.write(content)
        if not content.endswith("\n"):
            out_handle.write("\n")
        out_handle.write("\n")
        written += 1
        total_bytes += size

    # Footer summary
    out_handle.write(SEPARATOR + "\n")
    out_handle.write("BUNDLE SUMMARY\n")
    out_handle.write(SEPARATOR + "\n")
    out_handle.write(f"  Files written         : {written}\n")
    out_handle.write(f"  Files skipped (large) : {skipped_large}\n")
    out_handle.write(f"  Files skipped (error) : {skipped_err}\n")
    out_handle.write(f"  Total embedded bytes  : {total_bytes}\n")

    return written, skipped_large, skipped_err


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Combine project source files into a single text bundle for AI ingestion.",
    )
    parser.add_argument(
        "output",
        nargs="?",
        default="combined_code_for_ai.txt",
        help="Output file path (default: combined_code_for_ai.txt). Ignored if --stdout.",
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Project root to walk (default: current directory).",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Write to stdout instead of a file.",
    )
    parser.add_argument(
        "--max-file-size",
        type=int,
        default=MAX_FILE_SIZE,
        help=f"Skip files larger than N bytes (default: {MAX_FILE_SIZE}).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])

    # Allow runtime override of the size cap.
    global MAX_FILE_SIZE
    MAX_FILE_SIZE = args.max_file_size

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"error: {root} is not a directory", file=sys.stderr)
        return 2

    if args.stdout:
        written, large, errs = combine(root, sys.stdout)
    else:
        out_path = Path(args.output).resolve()
        with out_path.open("w", encoding="utf-8", newline="\n") as fh:
            written, large, errs = combine(root, fh)
        print(
            f"Wrote {written} files to {out_path} "
            f"(skipped {large} large, {errs} errored).",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
